version: "3.9"

services:
  nginx:
    image: nginx:mainline-alpine-slim
    container_name: nginx_app
    ports:
      - 8200:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
  php:
    build:
      args:
        MYUSER: php-app
        MYGROUP: www-data
        MYUID: 1000
      context: ./php-fpm
    container_name: php_app
    expose:
      - 9000
    volumes:
      - ./src:/app
  db:
    image: mariadb
    container_name: db_app
    ports:
      - 3306:3306
    env_file:
      - ./db/env/db.env
    volumes:
      - ./db/data:/var/lib/mysql
